[phases.setup]
cmds = ['...', 'npm install -g corepack', 'corepack enable', 'corepack prepare pnpm@9 --activate']

[phases.install]
dependsOn = ['setup']
cmds = ['...']

[phases.build]
dependsOn = ['install']
cmds = ['...', 'bundle exec hanami db migrate', 'pnpm run build', 'bundle exec hanami assets precompile']

[start]
dependsOn = ['build']
cmd = 'rackup config.ru -p $PORT'
