[phases.setup]
cmds = ['...', 'npm install -g pnpm@9']

[phases.install]
dependsOn = ['setup']
cmds = ['...', 'pnpm install']

[phases.build]
dependsOn = ['install']
cmds = ['...', 'bundle exec hanami db migrate', 'pnpm run build', 'bundle exec hanami assets precompile']

[start]
dependsOn = ['build']
cmd = 'rackup config.ru -p $PORT'
