# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # STEP 1 - CHECKOUT REPO
      - name: Checkout Repo
        uses: actions/checkout@v3

      # STEP 2 - INSTALL RUBY
      # will use Ruby version from the repo (either .ruby-version or Gemfile, not entirely sure)
      - name: Install Ruby
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          # setting this to "true" also runs "bundle install"
          bundler-cache: true

      # STEP 3 - LINT STYLES
      - name: Lint Styles
        run: bundle exec rake lint:style

      # STEP 4 - LINT SMELLS
      - name: Lint Smells
        run: bundle exec rake lint:smell
